import type { NextPage } from 'next'
import Head from 'next/head'
import Feed from '../components/Feed';
import Header from '../components/Header';
import Modal from '../components/Modal';

const Home: NextPage = () => {

    return (
        <div className="h-screen overflow-y-scroll scrollar-hide">
            <Head>
                <title>Instagram 3.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> 
            {/* Header */}
            <Header/>

            {/* Feed */}
            <Feed/>
            <Modal/>
        </div>
    )
}

export default Home;
